source 'http://rubygems.org'

gem 'mysql2'

gem 'rails', '3.1.1'
gem 'hpricot'
gem 'kaminari'
gem 'haml'
gem 'compass'
gem 'jquery-rails'
gem 'mini_magick'
gem 'mini_fb'
gem 'friendly_id'
gem 'acts-as-taggable-on'
gem 'amazon-ecs', :require=>'amazon/ecs'
gem 'sitemap_generator'
gem 'googlecharts'
gem 'aws-ses', '~> 0.4.1', :require => 'aws/ses'
gem 'recaptcha', :require => "recaptcha/rails"
gem 'rabl'
gem 'json'
#gem 'oauth2_provider'