source 'http://rubygems.org'

gem 'mysql2'

gem 'rails', '3.0.1'
gem 'haml'
gem 'compass'
gem 'will_paginate'
gem 'jquery-rails'
gem 'mini_magick'
gem 'twitter', '1.1.2'
gem 'mini_fb'
gem 'friendly_id'
gem 'acts-as-taggable-on'
gem 'amazon-ecs', :require=>'amazon/ecs'
gem 'sitemap_generator'
gem 'tiny_mce'
gem 'googlecharts'
gem 'aws-ses', '~> 0.4.1', :require => 'aws/ses'
gem 'recaptcha', :require => "recaptcha/rails"
