development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: ct_dev
 pool: 5
 username: root
 password:
 socket: /tmp/mysql.sock

test:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: ct_test
 pool: 5
 username: root
 password:
 socket: /tmp/mysql.sock

production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: ct_prod
 pool: 5
 username: root
 password:
 socket: /tmp/mysql.sock
