development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cherry_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cherry_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cherry_prod
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock