# Here you can specify default options for TinyMCE across all controllers
#
width: 640
height: 480
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_buttons1: 'formatselect,justifyleft,justifycenter,justifyright,justifyfull,indent,outdent,|,bold,italic,strikethrough,backcolor,forecolor,blockquote,charmap,bullist,numlist,removeformat, hr,|,link,unlink,anchor,image,styleprops,|,code'
theme_advanced_buttons2: ''
theme_advanced_buttons3: ''
plugins:
   - style
   - table
   - fullscreen
